name: Copy all src/* except index to cdn branch

on:
   push:
      branches: [master]
   pull_request:
      branches: [master]

jobs:
   copy:
      name: Copy all src/* except index to cdn branch
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: copy
           env:
              SRC_FOLDER_PATH: "src/components src/constants src/services src/utils src/views src/theme"
              TARGET_BRANCH: "cdn"
           run: |
              files=$(find $SRC_FOLDER_PATH -type f) # get the file list
              git config --global user.name 'zestio-io'
              git config --global user.email 'zesty@zesty-io.com'
              git fetch                         # fetch branches
              git checkout $TARGET_BRANCH       # checkout to your branch
              git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
              git add -A
              git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
              git push origin $TARGET_BRANCH # push to remote branch
