name: Live editor CI Dev
on:
   push:
      branches: [main]
   pull_request:
      branches: [main]
   workflow_dispatch:
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v1
           with:
              node-version: "14.x"
         - name: Install Dependencies
           run: npm ci
         - name: Check Eslint Types Prettier
           run: npm run test-all
         - name: Build Project
           run: npm run build
         - name: Run Tests
           run: npm run test
