name: Live editor CI Dev
on:
   push:
      branches: [main]
   pull_request:
      branches: [main]
   workflow_dispatch:
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v1
           with:
              node-version: "14.x"
         - name: Install NPM dependencies build
           run: npm  install
         - name: Check eslint types prettier
           run: npm run test-all
         - name: Run build
           run: npm run build
