name: Purge Cdn Cache
on:
   workflow_dispatch:
jobs:
   purge-jsdelivr-cache:
      runs-on: ubuntu-20.04
      steps:
         - uses: gacts/purge-jsdelivr-cache@v1
           with:
              url: |
                 https://cdn.jsdelivr.net/gh/zesty-io/live-editor@latest/dist/live-editor.production.js
